version: '3'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    # ojo esto es para que no de problemas de permisos en el nexus-data
    user: "1000:1000"
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g
    restart: always
